apiVersion: dns.cav.enablers.ob/v1alpha1
kind: RRset
metadata:
  labels:
    app.kubernetes.io/name: powerdns-operator
    app.kubernetes.io/managed-by: kustomize
  name: test.helloworld.com
spec:
  comment: nothing to tell
  type: A
  ttl: 300
  records:
    - 1.1.1.1
    - 2.2.2.2
  zoneRef:
    name: helloworld.com