version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    warn-unused: false
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: "api/*"
        linters:
          - lll
      - path: "internal/*"
        linters:
          - dupl
          - lll
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
    paths:
      - third_party$
      - builtin$
      - examples$
      - .git
      - .github
      - test
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
