site_name: PowerDNS Operator
site_url: https://powerdns-operator.github.io/powerdns-operator/
site_description: >-
  Manage PowerDNS from a Kubernetes cluster simple Custom Resources.
repo_url: https://github.com/powerdns-operator/PowerDNS-Operator
repo_name: PowerDNS Operator
copyright: |
  Copyright (c) PowerDNS-Operator contributors
  Copyright (c) 2025 Orange Business Services SA
theme:
  name: material
  features:
    - announce.dismiss # ??
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
  - toc:
      permalink: ⚓
  - pymdownx.snippets:
      base_path: docs/snippets
nav:
  - Introduction:
      - Introduction: index.md
      - Overview: introduction/overview.md
      - Getting started: introduction/getting-started.md
      - FAQ: introduction/faq.md
      - Stability and Support: introduction/stability-support.md
  - Guides:
      - ClusterZones: guides/clusterzones.md
      - Zones: guides/zones.md
      - ClusterRRsets: guides/clusterrrsets.md
      - RRsets: guides/rrsets.md
      - Metrics: guides/metrics.md
      - Warnings: guides/warnings.md
  - Testing Environment:
      - K3D: testing_environment/k3d.md
      - PowerDNS: testing_environment/powerdns.md
