---
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: soa.example.org
spec:
  name: example.org.
  records:
  - ns1.example.org. admin.example.org. 1 10800 3600 604800 3600
  ttl: 3600
  type: SOA
  zoneRef:
    name: example.org
    kind: ClusterZone
---
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: mx.example.org
spec:
  type: MX
  name: "example.org."
  ttl: 300
  records:
    - "10 mx1.example.org."
    - "20 mx2.example.org."
  zoneRef:
    name: example.org
    kind: ClusterZone
---
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: ns1.example.org
spec:
  type: A
  name: ns1
  ttl: 300
  records:
    - "10.25.32.1"
  zoneRef:
    name: example.org
    kind: ClusterZone
---
apiVersion: dns.cav.enablers.ob/v1alpha2
kind: ClusterRRset
metadata:
  name: ns2.example.org
spec:
  type: A
  name: ns2
  ttl: 300
  records:
    - "10.25.32.2"
  zoneRef:
    name: example.org
    kind: ClusterZone