# permissions for end users to edit clusterzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: powerdns-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterzone-editor-role
rules:
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - clusterzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - clusterzones/status
  verbs:
  - get
