# permissions for end users to view rrsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: powerdns-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: rrset-viewer-role
rules:
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - rrsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - rrsets/status
  verbs:
  - get
