# permissions for end users to view zones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: powerdns-operator
    app.kubernetes.io/managed-by: kustomize
  name: zone-viewer-role
rules:
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.cav.enablers.ob
  resources:
  - zones/status
  verbs:
  - get
