---
# Direct zone
apiVersion: dns.cav.enablers.ob/v1alpha1
kind: Zone
metadata:
  name: helloworld.com
spec:
  nameservers:
    - ns1.helloworld.com
    - ns2.helloworld.com
  kind: Native

---
# Reverse Zone
apiVersion: dns.cav.enablers.ob/v1alpha1
kind: Zone
metadata:
  name: 1.168.192.in-addr.arpa
spec:
  nameservers:
    - ns1.helloworld.com
    - ns2.helloworld.com
  kind: Native
